///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest5Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6bba731e-af31-4ffe-a223-1894584db42d")]
    public partial class MyTest5Repository : RepoGenBaseFolder
    {
        static MyTest5Repository instance = new MyTest5Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest5Repository element repository.
        /// </summary>
        [RepositoryFolder("6bba731e-af31-4ffe-a223-1894584db42d")]
        public static MyTest5Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest5Repository() 
            : base("MyTest5Repository", "/", null, 0, false, "6bba731e-af31-4ffe-a223-1894584db42d", ".\\RepositoryImages\\MyTest5Repository6bba731e.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6bba731e-af31-4ffe-a223-1894584db42d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest5RepositoryFolders
    {
    }
#pragma warning restore 0436
}
