///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("57e655ea-d5dc-4648-9443-264d3c600984", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest5Repository repository.
        /// </summary>
        public static MyTest5Repository repo = MyTest5Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.Female' at 43;5.", repo.FreeBMICalculator.FemaleInfo, new RecordItemIndex(0));
            repo.FreeBMICalculator.Female.Click("43;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.CalculateBMI' at 85;10.", repo.FreeBMICalculator.CalculateBMIInfo, new RecordItemIndex(1));
            repo.FreeBMICalculator.CalculateBMI.Click("85;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.Kilograms' at 69;16.", repo.FreeBMICalculator.KilogramsInfo, new RecordItemIndex(2));
            repo.FreeBMICalculator.Kilograms.Click("69;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.Text10201' at 41;6.", repo.FreeBMICalculator.Text10201Info, new RecordItemIndex(3));
            repo.FreeBMICalculator.Text10201.Click("41;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '54' with focus on 'FreeBMICalculator.Text10201'.", repo.FreeBMICalculator.Text10201Info, new RecordItemIndex(4));
            repo.FreeBMICalculator.Text10201.PressKeys("54");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.BMICalculatorGroupBoxWeightID4451939' at 45;84.", repo.FreeBMICalculator.BMICalculatorGroupBoxWeightID4451939Info, new RecordItemIndex(5));
            repo.FreeBMICalculator.BMICalculatorGroupBoxWeightID4451939.Click("45;84");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.Text10901' at 33;0.", repo.FreeBMICalculator.Text10901Info, new RecordItemIndex(6));
            repo.FreeBMICalculator.Text10901.Click("33;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.Text10901' at 57;13.", repo.FreeBMICalculator.Text10901Info, new RecordItemIndex(7));
            repo.FreeBMICalculator.Text10901.Click("57;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '75' with focus on 'FreeBMICalculator.Text10901'.", repo.FreeBMICalculator.Text10901Info, new RecordItemIndex(8));
            repo.FreeBMICalculator.Text10901.PressKeys("75");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FreeBMICalculator.CalculateBMI' at 76;10.", repo.FreeBMICalculator.CalculateBMIInfo, new RecordItemIndex(9));
            repo.FreeBMICalculator.CalculateBMI.Click("76;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
